---
title: "milestone_2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Project Review

For our assignment this week I reviewed two student projects--Jad Mayaah's "The Position of Women in the Middle East" and Janna Ramadan's "Perpetuating Islamophobia in the United States: Examining the Relationship Between News, Social Media, and Hate Crimes". 

Jad's project was particularly interesting for me because of my current regional focus and great interest in gender issues. I really like the way in which her first graph grouped by country (as opposed to try to fit it all the countries in one graph) and found that her fill choices for each position on the graph helped further emphasize the difference in responses. It was probably a small change, but it made the whole visual more aesthetically pleasing. Her second graph's grouping by prompt helped emphasize the nuances in public opninon amongst the countries included in the data set. I found her "religion and gender discrimiation" visual to be a bit confusing and harder to understand. While it may be reflected a positive correlation, the differences in the fill of the dots without any explanation were a bit confusing--maybe this graph would have benefitted from the inclusion of a legend. Overall, I found the project to be very informative and supportive of her key arguments.

I was immediately drawn to Jenna's project as my own undergraduate thesis looked at how media portrayal impacted viewers understanding of Arab women's agency within Middle Eastern conflict. Jenna's frst graphic on Islamophobia in the US was informative, but not as convincing as I would have liked. I beleive that the lack of data points, especially related to Anti-Arab sentiment weakened the visualization (but that isn't really her fault since the FBI didn't have records). Her use of animation in her media graph made for a more entertaining and active experience but I wish that I was able to see the dates featured on the x - axis. That way viewers could maybe see how policy or events during a certain period of time may have contributed towards spikes in the search of her selected terms. I really enjoyed her graphs exploring social media trends via twitter analysis and the different groupings that she incorporated. The one thing that I noticed was that her axis were mis-labelled for her "Word Associations By Key Word" graphs-- I think she forgot to chage them after flipping the x and y axis. I found her last visual on News Search Rates vs. Hate Crime Rates to be most interesting. I thought it was clever for her to join the two data sets and run her own models on the data.

Overall, looking through these two projects was a very informative experience and has provided me with some inspiration for my own final project.